# Inherit from ./DockerfileBase
FROM range3/cpp-boilerplate:latest

# RUN \
#   # Common packages
#   export DEBIAN_FRONTEND=noninteractive \
#   && apt-get update \
#   && apt-get -y install --no-install-recommends \
#     vim
#   # Clean up
#   && apt-get autoremove -y \
#   && apt-get clean -y \
#   && rm -rf /var/lib/apt/lists/*
