name: Build and Test

on:
  push:
    branches:
      - master
      - devel
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build and Test
        uses: ./.github/actions/cmake-build-test
