name: Build and Test

on:
  push:
    branches:
      - master
      - devel
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: ['Debug', 'Release']
        profile: ['default', 'clang']

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build and Test
        uses: ./.github/actions/cmake-build-test
        with:
          buildType: ${{ matrix.buildType }}
          profile: ${{ matrix.profile }}
